export const STATS = {
  datapoints: '500,000+',
  datapointsSub: 'on the road to 1 million',
  users: '100+',
  sectors: '15',
  foundingClaimed: 91,
  foundingTotal: 100,
  foundingLeft: 9,
  newsletterSubs: '594',
  linkedinFollowers: '2,512',
  launched: 'Feb 2026',
};

export const LINKS = {
  ai: 'https://ai.afrifoundry.com',
  foundingForm: 'https://tally.so/r/GxzR4k',
  contactForm: 'https://tally.so/r/contactAfriFoundry',
  newsletter: 'https://www.linkedin.com/newsletters/the-validation-point-7401988315769634816',
  linkedin: 'https://www.linkedin.com/in/markgakuya',
  twitter: 'https://twitter.com/AfriFoundry',
  whatsapp: 'https://whatsapp.com/channel/0029VbB1Yu07T8beQCLSJZ0I',
  email: 'mark@afrifoundry.com',
  phone: '+254 708 895 622',
};

export const FOUNDING_MEMBERS = [
  { num: '#001', name: 'Mark Gakuya', city: 'Mombasa' },
  { num: '#002', name: 'Founding Member', city: 'KE' },
  { num: '#003', name: 'Founding Member', city: 'KE' },
  { num: '#004', name: 'Founding Member', city: 'KE' },
  { num: '#005', name: 'Founding Member', city: 'NBI' },
  { num: '#006', name: 'Founding Member', city: 'KE' },
  { num: '#007', name: 'Founding Member', city: 'MSA' },
  { num: '#008', name: 'Founding Member', city: 'KE' },
  { num: '#009', name: 'Founding Member', city: 'NBI' },
  { num: '#010', name: 'Founding Member', city: 'KE' },
  { num: '#011', name: 'Founding Member', city: 'KE' },
  { num: '#012', name: 'Founding Member', city: 'NBI' },
  { num: '#013', name: 'Founding Member', city: 'KE' },
  { num: '#014', name: 'Founding Member', city: 'MSA' },
  { num: '#015', name: 'Founding Member', city: 'KE' },
  { num: '#016', name: 'Founding Member', city: 'KE' },
  { num: '#017', name: 'Founding Member', city: 'NBI' },
  { num: '#018', name: 'Founding Member', city: 'KE' },
  { num: '#019', name: 'Founding Member', city: 'KE' },
  { num: '#020', name: 'Founding Member', city: 'MSA' },
  { num: '#021', name: 'Founding Member', city: 'KE' },
  { num: '#022', name: 'Founding Member', city: 'KE' },
  { num: '#023', name: 'Founding Member', city: 'NBI' },
  { num: '#024', name: 'Founding Member', city: 'KE' },
  { num: '#025', name: 'Founding Member', city: 'KE' },
  { num: '#026', name: 'Founding Member', city: 'MSA' },
  { num: '#027', name: 'Founding Member', city: 'KE' },
  { num: '#028', name: 'Founding Member', city: 'KE' },
  { num: '#029', name: 'Founding Member', city: 'NBI' },
  { num: '#030', name: 'Founding Member', city: 'KE' },
  { num: '#031', name: 'Founding Member', city: 'KE' },
  { num: '#032', name: 'Founding Member', city: 'KE' },
  { num: '#033', name: 'Founding Member', city: 'MSA' },
  { num: '#034', name: 'Founding Member', city: 'KE' },
  { num: '#035', name: 'Founding Member', city: 'NBI' },
  { num: '#036', name: 'Founding Member', city: 'KE' },
  { num: '#037', name: 'Founding Member', city: 'KE' },
  { num: '#038', name: 'Founding Member', city: 'MSA' },
  { num: '#039', name: 'Founding Member', city: 'KE' },
  { num: '#040', name: 'Founding Member', city: 'KE' },
  { num: '#041', name: 'Founding Member', city: 'NBI' },
  { num: '#042', name: 'Founding Member', city: 'KE' },
  { num: '#043', name: 'Founding Member', city: 'KE' },
  { num: '#044', name: 'Founding Member', city: 'MSA' },
  { num: '#045', name: 'Founding Member', city: 'KE' },
  { num: '#046', name: 'Founding Member', city: 'KE' },
  { num: '#047', name: 'Founding Member', city: 'NBI' },
  { num: '#048', name: 'Founding Member', city: 'KE' },
  { num: '#049', name: 'Founding Member', city: 'KE' },
  { num: '#050', name: 'Founding Member', city: 'MSA' },
  { num: '#051', name: 'Founding Member', city: 'KE' },
  { num: '#052', name: 'Founding Member', city: 'KE' },
  { num: '#053', name: 'Founding Member', city: 'NBI' },
  { num: '#054', name: 'Founding Member', city: 'KE' },
  { num: '#055', name: 'Founding Member', city: 'KE' },
  { num: '#056', name: 'Founding Member', city: 'MSA' },
  { num: '#057', name: 'Founding Member', city: 'KE' },
  { num: '#058', name: 'Founding Member', city: 'KE' },
  { num: '#059', name: 'Founding Member', city: 'NBI' },
  { num: '#060', name: 'Founding Member', city: 'KE' },
  { num: '#061', name: 'Founding Member', city: 'KE' },
  { num: '#062', name: 'Founding Member', city: 'MSA' },
  { num: '#063', name: 'Founding Member', city: 'KE' },
  { num: '#064', name: 'Founding Member', city: 'KE' },
  { num: '#065', name: 'Founding Member', city: 'NBI' },
  { num: '#066', name: 'Founding Member', city: 'KE' },
  { num: '#067', name: 'Founding Member', city: 'KE' },
  { num: '#068', name: 'Founding Member', city: 'MSA' },
  { num: '#069', name: 'Founding Member', city: 'KE' },
  { num: '#070', name: 'Founding Member', city: 'KE' },
  { num: '#071', name: 'Founding Member', city: 'NBI' },
  { num: '#072', name: 'Founding Member', city: 'KE' },
  { num: '#073', name: 'Founding Member', city: 'KE' },
  { num: '#074', name: 'Founding Member', city: 'MSA' },
  { num: '#075', name: 'Founding Member', city: 'KE' },
  { num: '#076', name: 'Founding Member', city: 'KE' },
  { num: '#077', name: 'Founding Member', city: 'NBI' },
  { num: '#078', name: 'Founding Member', city: 'KE' },
  { num: '#079', name: 'Founding Member', city: 'KE' },
  { num: '#080', name: 'Founding Member', city: 'MSA' },
  { num: '#081', name: 'Founding Member', city: 'KE' },
  { num: '#082', name: 'Founding Member', city: 'KE' },
  { num: '#083', name: 'Founding Member', city: 'NBI' },
  { num: '#084', name: 'Founding Member', city: 'KE' },
  { num: '#085', name: 'Founding Member', city: 'KE' },
  { num: '#086', name: 'Founding Member', city: 'MSA' },
  { num: '#087', name: 'Founding Member', city: 'KE' },
  { num: '#088', name: 'Founding Member', city: 'KE' },
  { num: '#089', name: 'Founding Member', city: 'NBI' },
  { num: '#090', name: 'Founding Member', city: 'KE' },
  { num: '#091', name: 'Founding Member', city: 'KE' },
];
