export const STATS = {
  datapoints: '500,000+',
  datapointsSub: 'on the road to 1 million',
  datapointsTarget: '1,000,000',
  users: '100+',
  usersSub: 'since Feb 2026 launch',
  sectors: '15',
  foundingClaimed: 83,
  foundingTotal: 100,
  foundingLeft: 17,
  newsletterSubs: '594',
  linkedinFollowers: '2,512',
  launched: 'Feb 2026',
  founded: 'July 8, 2025',
};

export const LINKS = {
  ai: 'https://ai.afrifoundry.com',
  foundingForm: 'https://tally.so/r/GxzR4k',
  contactForm: 'https://tally.so/r/contactAfriFoundry',
  newsletter: 'https://www.linkedin.com/newsletters/the-validation-point-7401988315769634816',
  linkedin: 'https://www.linkedin.com/company/afrifoundry',
  founderLinkedin: 'https://www.linkedin.com/in/markgakuya',
  twitter: 'https://twitter.com/AfriFoundry',
  whatsapp: 'https://whatsapp.com/channel/0029VbB1Yu07T8beQCLSJZ0I',
  emailHello: 'hello@afrifoundry.com',
  emailAdmin: 'admin@afrifoundry.com',
  emailAI: 'ai@afrifoundry.com',
  emailSupport: 'support@afrifoundry.com',
  founderEmail: 'mark@afrifoundry.com',
  phone: '+254 708 895 622',
};

export const FOUNDING_MEMBERS = [
  { num: '#001', name: 'Mark Gakuya', city: 'Mombasa' },
  { num: '#002', name: 'Morris Kisanya', city: 'KE' },
  { num: '#003', name: 'Moyi Winnie Joy', city: 'KE' },
  { num: '#004', name: 'Daniel Oucho', city: 'KE' },
  { num: '#005', name: 'Diana Wangui Wanjiru', city: 'KE' },
  { num: '#006', name: 'Yusra Mohamed', city: 'KE' },
  { num: '#007', name: 'Kalii Mawioo', city: 'KE' },
  { num: '#008', name: 'Frankline Olango', city: 'KE' },
  { num: '#009', name: 'Joan Edesa', city: 'KE' },
  { num: '#010', name: 'Ian Muriuki', city: 'KE' },
  { num: '#011', name: 'James Nderema', city: 'KE' },
  { num: '#012', name: 'Esther', city: 'KE' },
  { num: '#013', name: 'Vivian Wangui', city: 'KE' },
  { num: '#014', name: 'Aidarus Mohamed Ali', city: 'KE' },
  { num: '#015', name: 'Jeesi Muguna Nteere', city: 'KE' },
  { num: '#016', name: 'Favour Wairimu', city: 'KE' },
  { num: '#017', name: 'Karani Njoroge', city: 'KE' },
  { num: '#018', name: 'Mike Kinyanjui', city: 'KE' },
  { num: '#019', name: 'Benard Kioko', city: 'KE' },
  { num: '#020', name: 'Benard Otieno', city: 'KE' },
  { num: '#021', name: 'Dennis Kisuko', city: 'KE' },
  { num: '#022', name: 'John Mutuma', city: 'KE' },
  { num: '#023', name: 'Ryan Maina', city: 'NBI' },
  { num: '#024', name: 'Michael Waweru', city: 'KE' },
  { num: '#025', name: 'Salame Khamis', city: 'MSA' },
  { num: '#026', name: 'Edward Kinyua', city: 'KE' },
  { num: '#027', name: 'Khamis Hussein', city: 'MSA' },
  { num: '#028', name: 'Anastacia David', city: 'KE' },
  { num: '#029', name: 'Muhammad Talib', city: 'KE' },
  { num: '#030', name: 'Charity Mwongeli Muthusi', city: 'KE' },
  { num: '#031', name: 'Naeem Dar', city: 'KE' },
  { num: '#032', name: 'Mutua Waithaka', city: 'KE' },
  { num: '#033', name: 'Angela Wambugha', city: 'KE' },
  { num: '#034', name: 'Patrick Mwangi', city: 'KE' },
  { num: '#035', name: 'Lucky Nzai', city: 'KE' },
  { num: '#036', name: 'Steve Mwangi', city: 'NBI' },
  { num: '#037', name: 'Stephen', city: 'KE' },
  { num: '#038', name: 'Olestern Munene Kariuki', city: 'KE' },
  { num: '#039', name: 'Kelvin Mutugi', city: 'KE' },
  { num: '#040', name: 'Engineer Fredrick Ondara', city: 'KE' },
  { num: '#041', name: 'Eric Mugendi', city: 'KE' },
  { num: '#042', name: 'Susan Bahati', city: 'KE' },
  { num: '#043', name: 'Collins Mukaria', city: 'KE' },
  { num: '#044', name: 'Hamisi Kanzere Mohammed', city: 'MSA' },
  { num: '#045', name: 'Daniel Mochoge', city: 'KE' },
  { num: '#046', name: 'Sialo', city: 'KE' },
  { num: '#047', name: 'Joel Sabore', city: 'KE' },
  { num: '#048', name: 'Caleb Gitonga', city: 'KE' },
  { num: '#049', name: 'Theuri Mwaniki', city: 'KE' },
  { num: '#050', name: 'Paul Kamau Njoroge', city: 'NBI' },
  { num: '#051', name: 'John Kihumba', city: 'KE' },
  { num: '#052', name: 'Brian Mwangi', city: 'KE' },
  { num: '#053', name: 'Shadrack Muinde', city: 'KE' },
  { num: '#054', name: 'Hildah Mitchelle', city: 'KE' },
  { num: '#055', name: 'Tumelo Mogagabe', city: 'KE' },
  { num: '#056', name: 'Brian Mbaja', city: 'KE' },
  { num: '#057', name: 'Jeremy Waweru', city: 'NBI' },
  { num: '#058', name: 'Keith Njoro', city: 'KE' },
  { num: '#059', name: 'Francis Muriithi', city: 'KE' },
  { num: '#060', name: 'Susan Mwangi', city: 'KE' },
  { num: '#061', name: 'Juliet Atieno Kesitah', city: 'KE' },
  { num: '#062', name: 'Owino Okowa Remmy Nyamweya', city: 'KE' },
  { num: '#063', name: 'Emmanuel Onyango', city: 'KE' },
  { num: '#064', name: 'Joseph Olango', city: 'KE' },
  { num: '#065', name: 'Reagan Muturi', city: 'NBI' },
  { num: '#066', name: 'Patson Muriuki Mungiria', city: 'KE' },
  { num: '#067', name: 'Steve Kibugi', city: 'KE' },
  { num: '#068', name: 'Bonventure Omondi', city: 'KE' },
  { num: '#069', name: 'Georgyne Kambona', city: 'KE' },
  { num: '#070', name: 'Seif Gharib', city: 'MSA' },
  { num: '#071', name: 'Esha Shally', city: 'KE' },
  { num: '#072', name: 'Mogulh Kiti', city: 'KE' },
  { num: '#073', name: 'Margaret Nyawira', city: 'KE' },
  { num: '#074', name: 'Jack Omondi Odhiambo', city: 'KE' },
  { num: '#075', name: 'Christian Omondi', city: 'KE' },
  { num: '#076', name: 'Jacob Juma', city: 'KE' },
  { num: '#077', name: 'Thaiya Waronja', city: 'KE' },
  { num: '#078', name: 'Daniel Mbugua', city: 'NBI' },
  { num: '#079', name: 'Elijah Fundi Kithinji', city: 'KE' },
  { num: '#080', name: 'James Nzau', city: 'KE' },
  { num: '#081', name: 'Daudi Ngoa', city: 'KE' },
  { num: '#082', name: 'Esther Wanjama', city: 'KE' },
  { num: '#083', name: 'Brian Mwangi', city: 'KE' },
];
